name: redis-guestbook
from:
  name: redis-guestbook
  version: 0.0.1
  repo: https://github.com/helm/charts
home: http://github.com/rimusz/charts/redis-guestbook
version: 0.0.1
description: Redis cluster to be used wtih the Guestbook App
maintainers:
- Rimas Mocevicius <rimas@deis.com>
details: This package provides a highly available Redis cluster with one master and 
  a replicated set of slaves
