{{- if not (empty .Values.serviceToken) }}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}-app
  labels:
    app: {{ template "fullname" . }}
    weavescope-component: {{ template "fullname" . }}-app
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}
        weavescope-component: {{ template "fullname" . }}-app
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
        release: "{{ .Release.Name }}"
        heritage: "{{ .Release.Service }}"
    spec:
      containers:
      - name: {{ template "fullname" . }}
        image: "weaveworks/scope:{{ .Values.imageTag }}"
        imagePullPolicy: {{ default "" .Values.imagePullPolicy | quote }}
        args:
        - --no-probe
        - --app.weave.addr=
        ports:
        - name: scope-app
          containerPort: 4040
          hostPort: 4040
{{- end }}
