apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: {{ template "fullname" . }}-probe
  labels:
    app: {{ template "fullname" . }}
    weavescope-component: {{ template "fullname" . }}-probe
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}
        weavescope-component: {{ template "fullname" . }}-probe
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
        release: "{{ .Release.Name }}"
        heritage: "{{ .Release.Service }}"
    spec:
      hostPID: true
      hostNetwork: true
      containers:
      - name: {{ template "fullname" . }}-probe
        image: "weaveworks/scope:{{ .Values.imageTag }}"
        imagePullPolicy: {{ default "" .Values.imagePullPolicy | quote }}
        args:
        - '--no-app'
        - '--probe.docker.bridge=cbr0'
        - '--probe.docker=true'
        - '--probe.kubernetes=true'
{{- if eq .Values.serviceToken "none" }}
        - '$(WEAVE_SCOPE_APP_SERVICE_HOST):$(WEAVE_SCOPE_APP_SERVICE_PORT)'{{ else }}
        - --probe.token={{.Values.serviceToken}}
{{- end}}
        securityContext:
          privileged: true
        resources:
          limits:
            cpu: 50m
        volumeMounts:
          - name: docker-sock
            mountPath: /var/run/docker.sock
      volumes:
      - name: docker-sock
        hostPath:
          path: /var/run/docker.sock
      - name: scope-plugins
        hostPath:
          path: /var/run/scope/plugins
