## cloudsql docker image version
##
image: b.gcr.io/cloudsql-docker/gce-proxy:1.05

## Specify a imagePullPolicy
## 'Always' if imageTag is 'latest', else set to 'IfNotPresent'
## ref: http://kubernetes.io/docs/user-guide/images/#pre-pulling-images
##
imagePullPolicy: IfNotPresent

## Replicas Set count
replicasCount: 1

## GCP service account key which cam access Cloud SQL instances
## the key must be encoded with base64
## e.g. `cat service-account.json | base64`
gcpServiceAccountKey: 'Paste base64 encoded data here.'

## SQL connection settings
##
cloudsql:
  ## PostgreSQL/MySQL instance
  ## update with your GCP project, the region of your Cloud SQL instance
  ## and the name of your Cloud SQL instance
  instance: "PROJECT:REGION:INSTANCE"

  ## PostgreSQL port 5432 or MySQL port 3306
  port: 5432

## Resource limits
cpu: 150m
memory: 200Mi
